<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import AppLayout from '../components/AppLayout.vue'
import ErrorAlert from '../components/ErrorAlert.vue'
import { supplierInvoicesApi } from '../api/supplierInvoices'
import { subcontractorsApi } from '../api/subcontractors'
import { referenceApi } from '../api/reference'
import { ApiError } from '../api/client'
import type { Currency, Subcontractor, SubcontractorCurrency } from '../api/types'

const router = useRouter()

const subcontractors = ref<Subcontractor[]>([])
const currencies = ref<Currency[]>([])
const allowedCurrencies = ref<SubcontractorCurrency[]>([])
const loadingReferenceData = ref(true)

const subcontractorId = ref('')
const supplierInvoiceNumber = ref('')
const invoiceDate = ref('')
const receivedDate = ref('')
const amount = ref(0)
const currencyId = ref('')

const error = ref('')
const submitting = ref(false)

const currencyOptions = computed(() => {
  const subcontractor = subcontractors.value.find((s) => s.id === subcontractorId.value)
  if (!subcontractor) return []
  const ids = new Set([subcontractor.currencyId, ...allowedCurrencies.value.map((sc) => sc.currencyId)])
  return currencies.value.filter((c) => ids.has(c.id))
})

watch(subcontractorId, async (id) => {
  currencyId.value = ''
  allowedCurrencies.value = []
  if (!id) return
  try {
    allowedCurrencies.value = await subcontractorsApi.currencies(id)
  } catch {
    // Non-fatal — the currency picker just falls back to the subcontractor's own primary.
  }
})

onMounted(async () => {
  try {
    const [subList, currencyList] = await Promise.all([subcontractorsApi.list(), referenceApi.currencies()])
    subcontractors.value = subList
    currencies.value = currencyList
  } catch (e) {
    error.value = e instanceof ApiError ? e.message : 'Could not load reference data.'
  } finally {
    loadingReferenceData.value = false
  }
})

async function submit() {
  error.value = ''
  submitting.value = true
  try {
    const invoice = await supplierInvoicesApi.create({
      subcontractorId: subcontractorId.value,
      supplierInvoiceNumber: supplierInvoiceNumber.value,
      invoiceDate: invoiceDate.value,
      receivedDate: receivedDate.value,
      amount: amount.value,
      currencyId: currencyId.value || undefined,
    })
    await router.push(`/supplier-invoices/${invoice.id}`)
  } catch (e) {
    error.value = e instanceof ApiError ? e.message : 'Something went wrong — please try again.'
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <AppLayout>
    <h1 class="text-xl font-semibold text-slate-900">Capture a supplier invoice</h1>
    <p class="mt-1 text-sm text-slate-500">The carrier's own invoice number and amount — never generated by this system.</p>

    <p v-if="loadingReferenceData" class="mt-6 text-sm text-slate-500">Loading…</p>

    <form v-else class="mt-6 flex max-w-lg flex-col gap-4" @submit.prevent="submit">
      <ErrorAlert v-if="error" :message="error" />

      <label class="flex flex-col gap-1 text-sm text-slate-700">
        Subcontractor
        <select v-model="subcontractorId" required class="rounded-md border border-slate-300 px-3 py-2 text-sm">
          <option value="" disabled>Select…</option>
          <option v-for="s in subcontractors" :key="s.id" :value="s.id">{{ s.name }}</option>
        </select>
      </label>

      <label class="flex flex-col gap-1 text-sm text-slate-700">
        Supplier invoice number
        <input v-model="supplierInvoiceNumber" type="text" required class="rounded-md border border-slate-300 px-3 py-2 text-sm" />
      </label>

      <div class="grid grid-cols-2 gap-4">
        <label class="flex flex-col gap-1 text-sm text-slate-700">
          Invoice date
          <input v-model="invoiceDate" type="date" required class="rounded-md border border-slate-300 px-3 py-2 text-sm" />
        </label>
        <label class="flex flex-col gap-1 text-sm text-slate-700">
          Received date
          <input v-model="receivedDate" type="date" required class="rounded-md border border-slate-300 px-3 py-2 text-sm" />
        </label>
      </div>

      <div class="grid grid-cols-2 gap-4">
        <label class="flex flex-col gap-1 text-sm text-slate-700">
          Amount
          <input v-model.number="amount" type="number" min="0.01" step="0.01" required class="rounded-md border border-slate-300 px-3 py-2 text-sm" />
        </label>
        <label class="flex flex-col gap-1 text-sm text-slate-700">
          Currency
          <select v-model="currencyId" :disabled="!subcontractorId" class="rounded-md border border-slate-300 px-3 py-2 text-sm">
            <option value="">Subcontractor's primary</option>
            <option v-for="c in currencyOptions" :key="c.id" :value="c.id">{{ c.code }}</option>
          </select>
        </label>
      </div>

      <div class="mt-2 flex gap-3">
        <button
          type="submit"
          :disabled="submitting"
          class="rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 disabled:opacity-50"
        >
          {{ submitting ? 'Capturing…' : 'Capture invoice' }}
        </button>
        <RouterLink to="/supplier-invoices" class="rounded-md border border-slate-300 px-4 py-2 text-sm text-slate-700 hover:bg-slate-100">
          Cancel
        </RouterLink>
      </div>
    </form>
  </AppLayout>
</template>
