using Tms.Shared;

namespace Tms.Modules.Billing;

public enum SubcontractorAccrualStatus
{
    Accrued,
    Netted
}

public enum SupplierInvoiceStatus
{
    Received,
    Matched,
    Disputed
}

public enum SubcontractorExpenseStatus
{
    AvailableToExport,
    Exported,
    Paid
}

/// <summary>
/// The buy-side liability for one buy RateLine, raised by LoadsController the moment
/// its leg is both Subcontracted and Allocated (docs/architecture.html §5.2, §10.2) —
/// long before POD/debrief, since the accrual basis recognises the liability at
/// commitment, not at settlement. A leg with two subcontracted lines (e.g. transport
/// plus an outsourced escort, §5.6) raises two independent accruals, each netted off
/// by its own SupplierInvoice match, possibly against two different subcontractors.
/// </summary>
public class SubcontractorAccrual : CompanyScopedEntity
{
    public Guid RateLineBuyId { get; set; }
    public Guid SubcontractorId { get; set; }
    public Guid CurrencyId { get; set; }
    public DateOnly AccrualDate { get; set; }
    public decimal EstimatedAmount { get; set; }
    public SubcontractorAccrualStatus Status { get; set; } = SubcontractorAccrualStatus.Accrued;
}

/// <summary>
/// The subcontractor's own invoice, captured when it arrives (§10.2) and matched
/// against one or more open Accrued accruals for that same subcontractor —
/// one-to-one for a single-leg invoice, one-to-many where a carrier bills several legs
/// together. SupplierInvoiceNumber is the carrier's own numbering, never generated by
/// this system, unlike Invoice.InvoiceNumber on the sell side.
/// </summary>
public class SupplierInvoice : CompanyScopedEntity
{
    public Guid SubcontractorId { get; set; }
    public Guid CurrencyId { get; set; }
    public string SupplierInvoiceNumber { get; set; } = string.Empty;
    public DateOnly InvoiceDate { get; set; }
    public DateOnly ReceivedDate { get; set; }
    public decimal Amount { get; set; }
    public SupplierInvoiceStatus Status { get; set; } = SupplierInvoiceStatus.Received;

    // Not in the doc's own field list, but capturing why an invoice was disputed is
    // obviously worth keeping — matches LoadConfirmation.DeclineReason, added for the
    // same reason.
    public string? DisputeReason { get; set; }

    public List<SubcontractorExpense> Expenses { get; set; } = new();
}

/// <summary>
/// The finalized, exportable cost for one buy RateLine, produced only by matching a
/// SupplierInvoice against its accrual (§10.2) — never created directly. Amount is the
/// actual invoiced apportionment, not the accrual's EstimatedAmount, so a variance
/// between the two is real and surfaced (on the match response) rather than silently
/// absorbed into whichever figure happened to be used.
/// </summary>
public class SubcontractorExpense : CompanyScopedEntity
{
    public Guid SubcontractorId { get; set; }
    public Guid CurrencyId { get; set; }
    public Guid RateLineBuyId { get; set; }
    public Guid AccrualId { get; set; }
    public Guid SupplierInvoiceId { get; set; }
    public Guid FinancialPeriodId { get; set; }
    public decimal Amount { get; set; }
    public SubcontractorExpenseStatus Status { get; set; } = SubcontractorExpenseStatus.AvailableToExport;
    public DateTimeOffset FinalizedDate { get; set; } = DateTimeOffset.UtcNow;
}
